import pytest
from sage.numerical.backends.generic_backend import GenericBackend as GenericBackend
from sage.structure.sage_object import SageObject as SageObject
from sage.structure.sage_object_test import SageObjectTests as SageObjectTests

class GenericBackendTests(SageObjectTests):
    @pytest.fixture
    def backend(self, *args, **kwargs) -> GenericBackend: ...
    @pytest.fixture
    def sage_object(self, backend) -> SageObject: ...
    def test_ncols_nonnegative(self, backend: GenericBackend): ...
    def test_sage_unittest_testsuite(self, sage_object: SageObject): ...
