from _typeshed import Incomplete
from sage.doctest.parsing import SageDocTestParser as SageDocTestParser, parse_optional_tags as parse_optional_tags

onlyLinux: Incomplete

def test_parse_optional_tags_known_bug_returns_bug() -> None: ...
def test_parse_optional_tags_known_bug_with_value_returns_bug_and_value() -> None: ...
def test_parse_optional_tags_known_bug_with_description_returns_bug() -> None: ...
def test_parse_optional_tags_known_bug_with_description_in_parentheses_returns_bug() -> None: ...
def test_parse_optional_tags_known_bug_with_value_and_description_returns_bug_and_value() -> None: ...
def test_parse_known_bug_returns_empty() -> None: ...
def test_parse_known_bug_returns_code_if_requested() -> None: ...
@onlyLinux
def test_parse_known_bug_returns_code_if_requested_even_on_affected_os() -> None: ...
@onlyLinux
def test_parse_known_bug_returns_code_on_not_affected_os() -> None: ...
@onlyLinux
def test_parse_known_bug_returns_empty_on_affected_os() -> None: ...
def test_parse_known_bug_with_description_returns_empty() -> None: ...
