import _cython_3_2_1
from sage.cpython.string import bytes_to_str as bytes_to_str, str_to_bytes as str_to_bytes

homfly_polynomial_dict: _cython_3_2_1.cython_function_or_method
homfly_polynomial_string: _cython_3_2_1.cython_function_or_method
