import pytest
from sage.manifolds.differentiable.examples.symplectic_space import StandardSymplecticSpace as StandardSymplecticSpace
from sage.manifolds.differentiable.symplectic_form import SymplecticForm as SymplecticForm

class TestR2VectorSpace:
    @pytest.fixture
    def M(self): ...
    @pytest.fixture
    def omega(self, M: StandardSymplecticSpace): ...
    def test_repr(self, M: StandardSymplecticSpace): ...
    def test_display(self, omega: SymplecticForm): ...

class TestR4VectorSpace:
    @pytest.fixture
    def M(self): ...
    @pytest.fixture
    def omega(self, M: StandardSymplecticSpace): ...
    def test_repr(self, M: StandardSymplecticSpace): ...
    def test_display(self, omega: SymplecticForm): ...
