from _typeshed import Incomplete
from sage.categories.action import PrecomposedAction as PrecomposedAction
from sage.misc.persist import register_unpickle_override as register_unpickle_override
from sage.misc.repr import repr_lincomb as repr_lincomb
from sage.modules.module import Module as Module
from sage.rings.integer_ring import ZZ as ZZ
from sage.structure.coerce_actions import LeftModuleAction as LeftModuleAction, RightModuleAction as RightModuleAction
from sage.structure.element import ModuleElement as ModuleElement
from sage.structure.parent import Parent as Parent
from sage.structure.richcmp import richcmp as richcmp
from sage.structure.unique_representation import UniqueRepresentation as UniqueRepresentation

class FormalSum(ModuleElement):
    """
    A formal sum over a ring.
    """
    def __init__(self, x, parent=None, check: bool = True, reduce: bool = True) -> None:
        """
        INPUT:

        - ``x`` -- object
        - ``parent`` -- FormalSums(R) module (default: FormalSums(ZZ))
        - ``check`` -- boolean (default: ``True``); if ``False``, might not coerce
          coefficients into base ring, which can speed up constructing a formal sum
        - ``reduce`` -- boolean (default: ``True``); if ``False``, do not
          combine common terms

        .. WARNING::

            Setting ``reduce`` to ``False`` can cause issues when comparing
            equal sums where terms are not combined in the same way (e.g.
            `2x + 3x` and `4x + 1x` will compare as not equal).

        EXAMPLES::

            sage: FormalSum([(1,2/3), (3,2/3), (-5, 7)])
            4*2/3 - 5*7
            sage: a = FormalSum([(1,2/3), (3,2/3), (-5, 7)], reduce=False); a
            2/3 + 3*2/3 - 5*7
            sage: a.reduce()
            sage: a
            4*2/3 - 5*7
            sage: FormalSum([(1, 2/3), (3, 2/3), (-5, 7)], parent=FormalSums(GF(5)))
            4*2/3

        Notice below that the coefficient 5 doesn't get reduced modulo 5::

            sage: FormalSum([(1, 2/3), (3, 2/3), (-5, 7)], parent=FormalSums(GF(5)),
            ....:           check=False)
            4*2/3 - 5*7

        Make sure we first reduce before checking coefficient types::

            sage: # needs sage.symbolic
            sage: x,y = var('x, y')
            sage: FormalSum([(1/2,x), (2,y)], FormalSums(QQ))
            1/2*x + 2*y
            sage: FormalSum([(1/2,x), (2,y)], FormalSums(ZZ))
            Traceback (most recent call last):
            ...
            TypeError: no conversion of this rational to integer
            sage: FormalSum([(1/2,x), (1/2,x), (2,y)], FormalSums(ZZ))
            x + 2*y
        """
    def __iter__(self):
        """
        EXAMPLES::

            sage: for z in FormalSum([(1, 2), (-3, 7), (5, 1000)]):
            ....:     print(z)
            (1, 2)
            (-3, 7)
            (5, 1000)
        """
    def __getitem__(self, n):
        """
        EXAMPLES::

            sage: v = FormalSum([(1, 2), (-3, 7), (5, 1000)]); v
            2 - 3*7 + 5*1000
            sage: v[0]
            (1, 2)
            sage: v[1]
            (-3, 7)
            sage: v[2]
            (5, 1000)
            sage: list(v)
            [(1, 2), (-3, 7), (5, 1000)]
        """
    def __len__(self) -> int:
        """
        EXAMPLES::

            sage: v = FormalSum([(1, 2), (5, 1000), (-3, 7)])
            sage: len(v)
            3
        """
    def __bool__(self) -> bool:
        """
        EXAMPLES::

            sage: bool(FormalSum([(1,3/7),(-2,5)]))
            True
            sage: bool(FormalSums(QQ)(0))
            False
            sage: bool(FormalSums(QQ)(1))
            True
        """
    def reduce(self) -> None:
        """
        EXAMPLES::

            sage: a = FormalSum([(-2,3), (2,3)], reduce=False); a
            -2*3 + 2*3
            sage: a.reduce()
            sage: a
            0
        """

class FormalSums(UniqueRepresentation, Module):
    """
    The R-module of finite formal sums with coefficients in some ring R.

    EXAMPLES::

        sage: FormalSums()
        Abelian Group of all Formal Finite Sums over Integer Ring
        sage: FormalSums(ZZ)
        Abelian Group of all Formal Finite Sums over Integer Ring
        sage: FormalSums(GF(7))
        Abelian Group of all Formal Finite Sums over Finite Field of size 7
        sage: FormalSums(ZZ[sqrt(2)])                                                   # needs sage.rings.number_field sage.symbolic
        Abelian Group of all Formal Finite Sums over
         Maximal Order generated by sqrt2 in Number Field in sqrt2
         with defining polynomial x^2 - 2 with sqrt2 = 1.414213562373095?
        sage: FormalSums(GF(9,'a'))                                                     # needs sage.rings.finite_rings
        Abelian Group of all Formal Finite Sums over Finite Field in a of size 3^2

    TESTS::

        sage: TestSuite(FormalSums(QQ)).run()
    """
    Element = FormalSum
    @staticmethod
    def __classcall__(cls, base_ring=...):
        """
        Set the default value for the base ring.

        EXAMPLES::

            sage: FormalSums(ZZ) == FormalSums()    # indirect test
            True
        """
    def base_extend(self, R):
        """
        EXAMPLES::

            sage: F7 = FormalSums(ZZ).base_extend(GF(7)); F7
            Abelian Group of all Formal Finite Sums over Finite Field of size 7

        The following tests against a bug that was fixed at :issue:`18795`::

            sage: isinstance(F7, F7.category().parent_class)
            True
        """

formal_sums: Incomplete
