import _cython_3_2_1
from sage.cpython.string import bytes_to_str as bytes_to_str, str_to_bytes as str_to_bytes
from sage.structure.element import have_same_parent as have_same_parent, parent as parent

__pyx_capi__: dict
facets_tuple_to_bit_rep_of_Vrep: _cython_3_2_1.cython_function_or_method
facets_tuple_to_bit_rep_of_facets: _cython_3_2_1.cython_function_or_method
incidence_matrix_to_bit_rep_of_Vrep: _cython_3_2_1.cython_function_or_method
incidence_matrix_to_bit_rep_of_facets: _cython_3_2_1.cython_function_or_method
