import os
file_path = os.path.dirname(__file__) + "/all.py"

import sage.all

f = open(file_path, "w")
print("# This file is autogenerated by `all-test.py`", file=f)

for name in dir(sage.all):
    if name.startswith("_"):
        continue
    print(f"from sage.all import {name} as {name}", file=f)

f.close()

