from sage.categories.groups import Groups as Groups
from sage.groups.matrix_gps.finitely_generated_gap import FinitelyGeneratedMatrixGroup_gap as FinitelyGeneratedMatrixGroup_gap
from sage.matrix.matrix_space import MatrixSpace as MatrixSpace
from sage.rings.integer_ring import ZZ as ZZ
from sage.rings.number_field.number_field import CyclotomicField as CyclotomicField
from sage.structure.unique_representation import UniqueRepresentation as UniqueRepresentation

class BinaryDihedralGroup(UniqueRepresentation, FinitelyGeneratedMatrixGroup_gap):
    """
    The binary dihedral group `BD_n` of order `4n`.

    Let `n` be a positive integer. The binary dihedral group `BD_n`
    is a finite group of order `4n`, and can be considered as the
    matrix group generated by

    .. MATH::

        g_1 = \\begin{pmatrix}
        \\zeta_{2n} & 0 \\\\ 0 & \\zeta_{2n}^{-1}
        \\end{pmatrix}, \\qquad\\qquad
        g_2 = \\begin{pmatrix} 0 & \\zeta_4 \\\\ \\zeta_4 & 0 \\end{pmatrix},

    where `\\zeta_k = e^{2\\pi i / k}` is the primitive `k`-th root of unity.
    Furthermore, `BD_n` admits the following presentation (note that there
    is a typo in [Sun2010]_):

    .. MATH::

        BD_n = \\langle x, y, z | x^2 = y^2 = z^n = x y z \\rangle.

    (The `x`, `y` and `z` in this presentations correspond to the
    `g_2`, `g_2 g_1^{-1}` and `g_1` in the matrix group
    avatar.)

    REFERENCES:

    - [Dol2009]_

    - [Sun2010]_

    - :wikipedia:`Dicyclic_group#Binary_dihedral_group`
    """
    def __init__(self, n) -> None:
        """
        Initialize ``self``.

        EXAMPLES::

            sage: G = groups.matrix.BinaryDihedral(4)
            sage: TestSuite(G).run()
        """
    def order(self):
        """
        Return the order of ``self``, which is `4n`.

        EXAMPLES::

            sage: G = groups.matrix.BinaryDihedral(3)
            sage: G.order()
            12

        TESTS::

            sage: for i in range(1, 10):
            ....:     G = groups.matrix.BinaryDihedral(5)
            ....:     assert len(list(G)) == G.order()
        """
    cardinality = order
