from sage.groups.matrix_gps.finitely_generated_gap import FinitelyGeneratedMatrixGroup_gap as FinitelyGeneratedMatrixGroup_gap
from sage.groups.matrix_gps.group_element_gap import MatrixGroupElement_gap as MatrixGroupElement_gap
from sage.groups.matrix_gps.linear import GL as GL, LinearMatrixGroup_generic as LinearMatrixGroup_generic
from sage.structure.sage_object import register_unpickle_override as register_unpickle_override

class LegacyMatrixGroup(FinitelyGeneratedMatrixGroup_gap): ...
class LegacyMatrixGroupElement(MatrixGroupElement_gap): ...
class LegacyGeneralLinearGroup(LinearMatrixGroup_generic): ...
