from sage.databases.db_class_polynomials import HilbertClassPolynomialDatabase as HilbertClassPolynomialDatabase
from sage.databases.db_modular_polynomials import AtkinModularCorrespondenceDatabase as AtkinModularCorrespondenceDatabase, AtkinModularPolynomialDatabase as AtkinModularPolynomialDatabase, ClassicalModularPolynomialDatabase as ClassicalModularPolynomialDatabase, DedekindEtaModularCorrespondenceDatabase as DedekindEtaModularCorrespondenceDatabase, DedekindEtaModularPolynomialDatabase as DedekindEtaModularPolynomialDatabase
from sage.databases.sql_db import SQLDatabase as SQLDatabase, SQLQuery as SQLQuery
from sage.misc.lazy_import import lazy_import as lazy_import
