import _cython_3_2_1
from sage.structure.element import have_same_parent as have_same_parent, parent as parent

gen_to_sage_matrix: _cython_3_2_1.cython_function_or_method
pari_typ_to_entries_type: _cython_3_2_1.cython_function_or_method
