import _cython_3_2_1
from sage.cpython.string import bytes_to_str as bytes_to_str, str_to_bytes as str_to_bytes
from sage.structure.element import have_same_parent as have_same_parent, parent as parent

__pyx_capi__: dict
coset_rep: _cython_3_2_1.cython_function_or_method
test_get_aut_gp_and_can_lab_trivially: _cython_3_2_1.cython_function_or_method
test_intersect_parabolic_with_alternating: _cython_3_2_1.cython_function_or_method
