import _cython_3_2_1
from sage.rings.complex_interval_field import ComplexIntervalField as ComplexIntervalField
from sage.rings.real_mpfi import RealIntervalField as RealIntervalField

refine_root: _cython_3_2_1.cython_function_or_method
