import _cython_3_2_1
from sage.cpython.string import bytes_to_str as bytes_to_str, str_to_bytes as str_to_bytes
from sage.graphs.base.boost_graph import boost_shortest_paths as boost_shortest_paths
from sage.structure.element import have_same_parent as have_same_parent, parent as parent

centrality_betweenness: _cython_3_2_1.cython_function_or_method
centrality_closeness_random_k: _cython_3_2_1.cython_function_or_method
centrality_closeness_top_k: _cython_3_2_1.cython_function_or_method
