import _cython_3_2_1
from sage.structure.element import have_same_parent as have_same_parent, parent as parent

is_line_graph: _cython_3_2_1.cython_function_or_method
line_graph: _cython_3_2_1.cython_function_or_method
root_graph: _cython_3_2_1.cython_function_or_method
