from IPython.terminal.prompts import Prompts

class SagePrompts(Prompts):
    def in_prompt_tokens(self, cli=None): ...
    def continuation_prompt_tokens(self, cli=None, width=None): ...
    def rewrite_prompt_tokens(self): ...
    def out_prompt_tokens(self): ...

class InterfacePrompts(Prompts):
    def __init__(self, interface_name) -> None: ...
    def in_prompt_tokens(self, cli=None): ...
    def continuation_prompt_tokens(self, cli=None, width=None): ...
    def rewrite_prompt_tokens(self): ...
    def out_prompt_tokens(self): ...

class DebugPrompts(Prompts):
    def in_prompt_tokens(self, cli=None): ...
    def continuation_prompt_tokens(self, cli=None, width=None): ...
    def rewrite_prompt_tokens(self): ...
    def out_prompt_tokens(self): ...
