from sage.cli.notebook_cmd import JupyterNotebookCmd as JupyterNotebookCmd

def test_jupyter_as_default() -> None: ...
def test_jupyter_explicitly() -> None: ...
def test_jupyterlab_explicitly() -> None: ...
def test_invalid_notebook_choice() -> None: ...
def test_help() -> None: ...
