from dataclasses import dataclass

@dataclass
class CliOptions:
    """
    A TypedDict for command-line interface options.
    """
    verbose: bool = ...
    quiet: bool = ...
    simple_prompt: bool = ...
    notebook: str = ...
    command: str | None = ...
    file: str | None = ...
