import pytest
from _pytest.fixtures import FixtureRequest as FixtureRequest
from sage.manifolds.differentiable.examples.sphere import Sphere as Sphere
from sage.manifolds.differentiable.examples.symplectic_space import StandardSymplecticSpace as StandardSymplecticSpace
from sage.manifolds.differentiable.manifold import DifferentiableManifold as DifferentiableManifold
from sage.manifolds.differentiable.scalarfield import DiffScalarField as DiffScalarField
from sage.manifolds.differentiable.symplectic_form import SymplecticForm as SymplecticForm
from sage.manifolds.manifold import Manifold as Manifold
from sage.symbolic.function_factory import function as function

class TestGenericSymplecticForm:
    @pytest.fixture
    def omega(self): ...
    def test_repr(self, omega: SymplecticForm): ...
    def test_new_instance_repr(self, omega: SymplecticForm): ...
    def test_new_instance_same_type(self, omega: SymplecticForm): ...
    def test_new_instance_same_parent(self, omega: SymplecticForm): ...
    def test_init_derived_sets_poisson_tensor(self, omega: SymplecticForm): ...
    def test_del_derived_resets_poisson_tensor(self, omega: SymplecticForm): ...

class TestCoherenceOfFormulas:
    """
    Test correctness of the implementation, by checking that equivalent formulas give the correct result.
    We check it for the examples of `\\R^2` and `S^2`, which should be enough.
    """
    def M(self, request: FixtureRequest): ...
    def omega(self, M): ...
    def test_flat_of_hamiltonian_vector_field(self, M: DifferentiableManifold, omega: SymplecticForm): ...
    def test_hamiltonian_vector_field_contr_symplectic_form(self, M: DifferentiableManifold, omega: SymplecticForm): ...
    def test_poisson_bracket_as_contraction_symplectic_form(self, M: DifferentiableManifold, omega: SymplecticForm): ...
    def test_poisson_bracket_as_contraction_poisson_tensor(self, M: DifferentiableManifold, omega: SymplecticForm): ...
    def test_poisson_bracket_as_contraction_hamiltonian_vector_field(self, M: DifferentiableManifold, omega: SymplecticForm): ...
    def test_poisson_bracket_as_commutator_hamiltonian_vector_fields(self, M: DifferentiableManifold, omega: SymplecticForm): ...
    def test_hodge_star_of_one_is_volume(self, M: DifferentiableManifold, omega: SymplecticForm): ...
    def test_hodge_star_of_volume_is_one(self, M: DifferentiableManifold, omega: SymplecticForm): ...
    def test_trace_of_two_form_is_given_using_contraction_with_omega(self, M: DifferentiableManifold, omega: SymplecticForm): ...
    def test_omega_on_forms_is_determinant_for_decomposables(self, M: DifferentiableManifold, omega: SymplecticForm): ...
    def test_omega_on_one_forms_is_omega_on_dual_vectors(self, M: DifferentiableManifold, omega: SymplecticForm): ...

def generic_scalar_field(M: DifferentiableManifold, name: str) -> DiffScalarField: ...

class TestR2VectorSpace:
    @pytest.fixture
    def M(self): ...
    @pytest.fixture
    def omega(self, M): ...
    def test_display(self, omega: SymplecticForm): ...
    def test_poisson(self, omega: SymplecticForm): ...
    def test_hamiltonian_vector_field(self, M: StandardSymplecticSpace, omega: SymplecticForm): ...
    def test_flat(self, M: StandardSymplecticSpace, omega: SymplecticForm): ...
    def test_hodge_star(self, M: StandardSymplecticSpace, omega: SymplecticForm): ...
    def test_omega_on_one_forms(self, M: StandardSymplecticSpace, omega: SymplecticForm): ...
    def test_hodge_star_is_given_using_omega_on_forms(self, M: StandardSymplecticSpace, omega: SymplecticForm): ...
