from _typeshed import Incomplete

def list_function(x): ...
def tuple_function(x): ...
def bool_function(x): ...
def str_function(x): ...

mathml_table: Incomplete

class MathML(str): ...

def mathml(x):
    """
    Output x formatted for inclusion in a MathML document.
    """
