from typing import Literal, Protocol, Self
from sage.structure.parent_gens import ParentWithGens
from sage.structure.sage_object import SageObject

class ElementWithGens(Protocol):
    def parent(self) -> ParentWithGens: ...

class CallableArgs[Arg, ReturnT](Protocol):
    def __call__(self, *args: Arg) -> ReturnT:
        ...

class StrictlyComparable(Protocol):
    def __lt__(self, other: Self) -> bool: ...
    def __gt__(self, other: Self) -> bool: ...

class NonStrictlyComparable(Protocol):
    def __le__(self, other: Self) -> bool: ...
    def __ge__(self, other: Self) -> bool: ...

class Comparable(NonStrictlyComparable, StrictlyComparable):
    ...

class ComparableWithZero(Protocol):
    def __lt__(self, zero: Literal[0]) -> bool: ...
    def __gt__(self, zero: Literal[0]) -> bool: ...
    def __le__(self, zero: Literal[0]) -> bool: ...
    def __ge__(self, zero: Literal[0]) -> bool: ...

class Addable(Protocol):
    def __add__(self, other: Self) -> Self:
        ...

class AddableWith[A](Protocol):
    def __add__(self, a: A) -> Self:
        ...

class AddableWithExt[A, S](Protocol):
    def __add__(self, a: A) -> S:
        ...

class Multiplicable(Protocol):
    def __mul__(self, other: Self) -> Self:
        ...

class MultiplicableWith[M](Protocol):
    def __mul__(self, m: M) -> Self:
        ...

class MultiplicableWithExt[M, P](Protocol):
    def __mul__(self, a: M) -> P:
        ...

class SupportsSage(Protocol):
    def _sage_(self) -> SageObject: ...