from typing import Literal, Protocol, Self
from collections.abc import Iterable
from sage.structure.parent_gens import ParentWithGens
from sage.structure.sage_object import SageObject

class ElementWithGens(Protocol):
    def parent(self) -> ParentWithGens: ...

class CallableArgs[Arg, ReturnT](Protocol):
    def __call__(self, *args: Arg) -> ReturnT:
        ...

class StrictlyComparable(Protocol):
    def __lt__(self, other: Self) -> bool: ...
    def __gt__(self, other: Self) -> bool: ...

class NonStrictlyComparable(Protocol):
    def __le__(self, other: Self) -> bool: ...
    def __ge__(self, other: Self) -> bool: ...

class Comparable(NonStrictlyComparable, StrictlyComparable):
    ...

class ComparableWithZero(Protocol):
    def __lt__(self, zero: Literal[0]) -> bool: ...
    def __gt__(self, zero: Literal[0]) -> bool: ...
    def __le__(self, zero: Literal[0]) -> bool: ...
    def __ge__(self, zero: Literal[0]) -> bool: ...

class Addable(Protocol):
    def __add__(self, other: Self) -> Self:
        ...

class AddableWith[A](Protocol):
    def __add__(self, a: A) -> Self:
        ...

class AddableWithExt[A, S](Protocol):
    def __add__(self, a: A) -> S:
        ...

class Multiplicable(Protocol):
    def __mul__(self, other: Self) -> Self:
        ...

class MultiplicableWith[M](Protocol):
    def __mul__(self, m: M) -> Self:
        ...

class MultiplicableWithExt[M, P](Protocol):
    def __mul__(self, a: M) -> P:
        ...

class SupportsPowWithExponent[E, P](Protocol):
    def __pow__(self, e: E) -> P: ...

class SupportsRPowWithBase[B, P](Protocol):
    def __rpow__(self, b: B) -> P: ...

class SupportsSage(Protocol):
    def _sage_(self) -> SageObject: ...

class SupportsKeysAndGetItem[KT, VT](Protocol):
    def keys(self) -> Iterable[KT]: ...
    def __getitem__(self, key: KT, /) -> VT: ...

class SupportsExp[T](Protocol):
    def exp(self) -> T: ...

class SupportsReal[T](Protocol):
    def real(self) -> T: ...

class SupportsRealPart[T](Protocol):
    def real_part(self) -> T: ...

class SupportsImag[T](Protocol):
    def imag(self) -> T: ...

class SupportsImagPart[T](Protocol):
    def imag_part(self) -> T: ...

class SupportsGamma[T](Protocol):
    def gamma(self) -> T: ...

class Supports__code__(Protocol):
    def __code__(self): ...