from sage.rings.polynomial.pbori.PyPolyBoRi import Polynomial as Polynomial

AUTO: str
SINGLE: str

def reencode_blocks(block_str): ...
def parse_blocks(block_str, data): ...
def load_ref_raw(s): ...
def load_ref(s, ordering: str = 'lp', blocks=...): ...
def ordering_suffix(o, blocks=None): ...
def number_of_declared_vars(data): ...
def load_ref_gz_uu(s, o, b): ...
def convert_refs(ref_file_orig) -> None: ...
def dyn_generate(content, name): ...
def clean_data(data) -> None: ...
def load_data(file_name, base_dir: str = './'): ...
def load_file(file_name): ...
