from _typeshed import Incomplete
from sage.rings.polynomial.pbori.PyPolyBoRi import BoolePolynomialVector as BoolePolynomialVector
from sage.rings.polynomial.pbori.blocks import Block as Block, declare_ring as declare_ring
from sage.rings.polynomial.pbori.pbori import BooleSet as BooleSet, Monomial as Monomial, Polynomial as Polynomial, Variable as Variable, add_up_polynomials as add_up_polynomials, interpolate as interpolate, interpolate_smallest_lex as interpolate_smallest_lex
from sage.rings.polynomial.pbori.randompoly import gen_random_poly as gen_random_poly

generator: Incomplete

def add_up_poly_list(l, init): ...
def bench_interpolate(degree, nvariables, points): ...
def nf_lex_points(f, p): ...
def gen_random_o_z(points, points_p): ...
def variety_lex_leading_terms(points, variables): ...
def lex_groebner_basis_points(points, variables): ...
def lex_groebner_basis_for_polynomial_via_variety(p): ...
