from sage.rings.polynomial.pbori.pbori import BooleanPolynomialRing as BooleanPolynomialRing, BooleanPolynomialVector as BooleanPolynomialVector, TermOrder_from_pb_order as TermOrder_from_pb_order, add_up_polynomials as add_up_polynomials

def Ring(n, order: str = 'lp', names=None, blocks=None): ...
BoolePolynomialVector = BooleanPolynomialVector

def WeakRingRef(ring): ...
def gauss_on_polys(l): ...
