from sage.rings.polynomial.pbori.pbori import BooleConstant as BooleConstant, Monomial as Monomial, Polynomial as Polynomial, top_index as top_index

def used_vars(l, bound=None): ...
def used_vars_set(l, bound=None): ...
