from __future__ import annotations
from mpmath.functions.functions import defun_wrapped
__all__: list[str] = ['defun_wrapped', 'sawtoothw', 'sigmoid', 'squarew', 'trianglew', 'unit_triangle']
def sawtoothw(ctx, t, amplitude = 1, period = 1):
    ...
def sigmoid(ctx, t, amplitude = 1):
    ...
def squarew(ctx, t, amplitude = 1, period = 1):
    ...
def trianglew(ctx, t, amplitude = 1, period = 1):
    ...
def unit_triangle(ctx, t, amplitude = 1):
    ...
