from sage.categories.lie_algebras import LieAlgebras as LieAlgebras
from sage.sets.family import Family as Family
from sage.structure.element_wrapper import ElementWrapper as ElementWrapper
from sage.structure.parent import Parent as Parent
from sage.structure.unique_representation import UniqueRepresentation as UniqueRepresentation

class LieAlgebraFromAssociative(Parent, UniqueRepresentation):
    """
    An example of a Lie algebra: a Lie algebra generated by
    a set of elements of an associative algebra.

    This class illustrates a minimal implementation of a Lie algebra.

    Let `R` be a commutative ring, and `A` an associative
    `R`-algebra. The Lie algebra `A` (sometimes denoted `A^-`)
    is defined to be the `R`-module `A` with Lie bracket given by
    the commutator in `A`: that is, `[a, b] := ab - ba` for all
    `a, b \\in A`.

    What this class implements is not precisely `A^-`, however;
    it is the Lie subalgebra of `A^-` generated by the elements
    of the iterable ``gens``. This specific implementation does not
    provide a reasonable containment test (i.e., it does not allow
    you to check if a given element `a` of `A^-` belongs to this
    Lie subalgebra); it, however, allows computing inside it.

    INPUT:

    - ``gens`` -- a nonempty iterable consisting of elements of an
      associative algebra `A`

    OUTPUT:

    The Lie subalgebra of `A^-` generated by the elements of
    ``gens``

    EXAMPLES:

    We create a model of `\\mathfrak{sl}_2` using matrices::

        sage: gens = [matrix([[0,1],[0,0]]), matrix([[0,0],[1,0]]), matrix([[1,0],[0,-1]])]
        sage: for g in gens:
        ....:     g.set_immutable()
        sage: L = LieAlgebras(QQ).example(gens)
        sage: e,f,h = L.lie_algebra_generators()
        sage: e.bracket(f) == h
        True
        sage: h.bracket(e) == 2*e
        True
        sage: h.bracket(f) == -2*f
        True
    """
    @staticmethod
    def __classcall_private__(cls, gens):
        """
        Normalize input to ensure a unique representation.

        EXAMPLES::

            sage: # needs sage.combinat sage.groups
            sage: S3 = SymmetricGroupAlgebra(QQ, 3)
            sage: L1 = LieAlgebras(QQ).example()
            sage: gens = list(S3.algebra_generators())
            sage: L2 = LieAlgebras(QQ).example(gens)
            sage: L1 is L2
            True
        """
    def __init__(self, gens) -> None:
        """
        EXAMPLES::

            sage: L = LieAlgebras(QQ).example()                                         # needs sage.combinat sage.groups
            sage: TestSuite(L).run()                                                    # needs sage.combinat sage.groups
        """
    def zero(self):
        """
        Return the element 0.

        EXAMPLES::

            sage: L = LieAlgebras(QQ).example()                                         # needs sage.combinat sage.groups
            sage: L.zero()                                                              # needs sage.combinat sage.groups
            0
        """
    def lie_algebra_generators(self):
        """
        Return the generators of ``self`` as a Lie algebra.

        EXAMPLES::

            sage: L = LieAlgebras(QQ).example()                                         # needs sage.combinat sage.groups
            sage: L.lie_algebra_generators()                                            # needs sage.combinat sage.groups
            Family ([2, 1, 3], [2, 3, 1])
        """
    class Element(ElementWrapper):
        """
        Wrap an element as a Lie algebra element.
        """
        def __eq__(self, rhs):
            """
            Check equality.

            This check is rather restrictive: ``self`` and ``rhs`` are only
            revealed as equal if they are equal *and* have the same parent
            (or both are zero).

            EXAMPLES::

                sage: # needs sage.combinat sage.groups
                sage: L = LieAlgebras(QQ).example()
                sage: x, y = L.lie_algebra_generators()
                sage: x == x
                True
                sage: x.bracket(y) == -y.bracket(x)
                True
                sage: x == y
                False
                sage: x.bracket(x) == L.zero()
                True
                sage: x.bracket(x) == 0
                True
            """
        def __ne__(self, rhs):
            """
            Check not-equals.

            EXAMPLES::

                sage: # needs sage.combinat sage.groups
                sage: L = LieAlgebras(QQ).example()
                sage: x, y = L.lie_algebra_generators()
                sage: x != y
                True
                sage: x != 0
                True
                sage: x != x
                False
                sage: x.bracket(y) != -y.bracket(x)
                False
            """
        def __hash__(self):
            """
            Return the hash of ``self``.

            EXAMPLES::

                sage: # needs sage.combinat sage.groups
                sage: L = LieAlgebras(QQ).example()
                sage: x, y = L.lie_algebra_generators()
                sage: hash(x) == hash(x.value)
                True
            """
        def __bool__(self) -> bool:
            """
            Check nonzero.

            EXAMPLES::

                sage: L = LieAlgebras(QQ).example()                                     # needs sage.combinat sage.groups
                sage: bool(sum(L.lie_algebra_generators()))                             # needs sage.combinat sage.groups
                True
                sage: bool(L.zero())                                                    # needs sage.combinat sage.groups
                False
            """
        def __truediv__(self, x, self_on_left: bool = False):
            """
            Division by coefficients.

            EXAMPLES::

                sage: L = LieAlgebras(QQ).example()                                     # needs sage.combinat sage.groups
                sage: x, y = L.lie_algebra_generators()                                 # needs sage.combinat sage.groups
                sage: y / 4                                                             # needs sage.combinat sage.groups
                1/4*[2, 3, 1]
            """
        def __neg__(self):
            """
            Return the negation of ``self``.

            EXAMPLES::

                sage: L = LieAlgebras(QQ).example()                                     # needs sage.combinat sage.groups
                sage: x, y = L.lie_algebra_generators()                                 # needs sage.combinat sage.groups
                sage: -x                                                                # needs sage.combinat sage.groups
                -[2, 1, 3]
            """
        def __getitem__(self, i):
            """
            Redirect the ``__getitem__()`` to the wrapped element.

            EXAMPLES::

                sage: gens = [matrix([[0,1],[0,0]]), matrix([[0,0],[1,0]]), matrix([[1,0],[0,-1]])]
                sage: for g in gens:
                ....:     g.set_immutable()
                sage: L = LieAlgebras(QQ).example(gens)
                sage: e,f,h = L.lie_algebra_generators()
                sage: h[0,0]
                1
                sage: h[1,1]
                -1
                sage: h[0,1]
                0
            """
Example = LieAlgebraFromAssociative
