from _typeshed import Incomplete
from sage.categories.magmas import Magmas as Magmas
from sage.misc.cachefunc import cached_method as cached_method
from sage.sets.family import Family as Family
from sage.structure.element_wrapper import ElementWrapper as ElementWrapper
from sage.structure.parent import Parent as Parent
from sage.structure.unique_representation import UniqueRepresentation as UniqueRepresentation

class FreeMagma(UniqueRepresentation, Parent):
    """
    An example of magma.

    The purpose of this class is to provide a minimal template for
    implementing a magma.

    EXAMPLES::

        sage: M = Magmas().example(); M
        An example of a magma: the free magma generated by ('a', 'b', 'c', 'd')

    This is the free magma generated by::

        sage: M.magma_generators()
        Family ('a', 'b', 'c', 'd')
        sage: a, b, c, d = M.magma_generators()

    and with a non-associative product given by::

        sage: a * (b * c) * (d * a * b)
        '((a*(b*c))*((d*a)*b))'
        sage: a * (b * c) == (a * b) * c
        False

    TESTS::

        sage: TestSuite(M).run()
    """
    alphabet: Incomplete
    def __init__(self, alphabet=('a', 'b', 'c', 'd')) -> None:
        """
        The free magma.

        INPUT:

        - ``alphabet`` -- tuple of strings; the generators of the magma

        EXAMPLES::

            sage: from sage.categories.examples.magmas import FreeMagma
            sage: F = FreeMagma(('a', 'b', 'c')); F
            An example of a magma: the free magma generated by ('a', 'b', 'c')

        TESTS::

            sage: F == loads(dumps(F))
            True
        """
    def product(self, x, y):
        """
        Return the product of ``x`` and ``y`` in the magma, as per
        :meth:`Magmas.ParentMethods.product`.

        EXAMPLES::

            sage: F = Magmas().example()
            sage: F('a') * F.an_element()
            '(a*(((a*b)*c)*d))'
        """
    @cached_method
    def magma_generators(self):
        """
        Return the generators of the magma.

        EXAMPLES::

            sage: F = Magmas().example()
            sage: F.magma_generators()
            Family ('a', 'b', 'c', 'd')
        """
    def an_element(self):
        """
        Return an element of the magma.

        EXAMPLES::

            sage: F = Magmas().example()
            sage: F.an_element()
            '(((a*b)*c)*d)'
        """
    class Element(ElementWrapper):
        """
        The class for elements of the free magma.
        """
        wrapped_class = str
Example = FreeMagma
