import _cython_3_2_1
from sage.cpython.string import bytes_to_str as bytes_to_str, str_to_bytes as str_to_bytes
from sage.matroids.dual_matroid import DualMatroid as DualMatroid
from sage.matroids.gammoid import Gammoid as Gammoid
from sage.matroids.minor_matroid import MinorMatroid as MinorMatroid
from sage.misc.persist import register_unpickle_override as register_unpickle_override
from sage.structure.element import have_same_parent as have_same_parent, parent as parent

unpickle_basis_matroid: _cython_3_2_1.cython_function_or_method
unpickle_binary_matrix: _cython_3_2_1.cython_function_or_method
unpickle_binary_matroid: _cython_3_2_1.cython_function_or_method
unpickle_circuit_closures_matroid: _cython_3_2_1.cython_function_or_method
unpickle_circuits_matroid: _cython_3_2_1.cython_function_or_method
unpickle_dual_matroid: _cython_3_2_1.cython_function_or_method
unpickle_flats_matroid: _cython_3_2_1.cython_function_or_method
unpickle_gammoid: _cython_3_2_1.cython_function_or_method
unpickle_generic_matrix: _cython_3_2_1.cython_function_or_method
unpickle_graphic_matroid: _cython_3_2_1.cython_function_or_method
unpickle_linear_matroid: _cython_3_2_1.cython_function_or_method
unpickle_minor_matroid: _cython_3_2_1.cython_function_or_method
unpickle_plus_minus_one_matrix: _cython_3_2_1.cython_function_or_method
unpickle_quaternary_matrix: _cython_3_2_1.cython_function_or_method
unpickle_quaternary_matroid: _cython_3_2_1.cython_function_or_method
unpickle_rational_matrix: _cython_3_2_1.cython_function_or_method
unpickle_regular_matroid: _cython_3_2_1.cython_function_or_method
unpickle_ternary_matrix: _cython_3_2_1.cython_function_or_method
unpickle_ternary_matroid: _cython_3_2_1.cython_function_or_method
unpickle_transversal_matroid: _cython_3_2_1.cython_function_or_method
