import _cython_3_2_1
import sage.rings.ring
from typing import Any, ClassVar, overload

is_NumberField: _cython_3_2_1.cython_function_or_method

class NumberField(sage.rings.ring.Field):
    """File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 49)

        Base class for all number fields.

        TESTS::

            sage: x = polygen(ZZ)
            sage: k = NumberField(x^2 + 1, 'i')
            sage: k == loads(dumps(k))
            True

            sage: z = polygen(QQ)
            sage: K.<theta, beta> = NumberField([z^3 - 3, z^2 + 1])
            sage: K.is_finite()
            False
            sage: K.order()
            +Infinity
    """
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None:
        """Create and return a new object.  See help(type) for accurate signature."""
    @overload
    def OK(self, *args, **kwds) -> Any:
        """NumberField.OK(self, *args, **kwds)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 166)

        Synonym for :meth:`maximal_order`.

        EXAMPLES::

            sage: x = polygen(ZZ)
            sage: NumberField(x^3 - 2,'a').OK()
            Maximal Order generated by a in Number Field in a with defining polynomial x^3 - 2"""
    @overload
    def OK(self) -> Any:
        """NumberField.OK(self, *args, **kwds)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 166)

        Synonym for :meth:`maximal_order`.

        EXAMPLES::

            sage: x = polygen(ZZ)
            sage: NumberField(x^3 - 2,'a').OK()
            Maximal Order generated by a in Number Field in a with defining polynomial x^3 - 2"""
    @overload
    def bach_bound(self) -> Any:
        """NumberField.bach_bound(self)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 325)

        Return the Bach bound associated to this number field.

        Assuming the General Riemann Hypothesis, this is a bound `B` so
        that every integral ideal is equivalent modulo principal
        fractional ideals to an integral ideal of norm at most `B`.

        .. SEEALSO::

            :meth:`~minkowski_bound`

        OUTPUT: symbolic expression or the Integer 1

        EXAMPLES:

        We compute both the Minkowski and Bach bounds for a quadratic
        field, where the Minkowski bound is much better::

            sage: # needs sage.symbolic
            sage: K = QQ[sqrt(5)]
            sage: K.minkowski_bound()
            1/2*sqrt(5)
            sage: K.minkowski_bound().n()
            1.11803398874989
            sage: K.bach_bound()
            12*log(5)^2
            sage: K.bach_bound().n()
            31.0834847277628

        We compute both the Minkowski and Bach bounds for a bigger
        degree field, where the Bach bound is much better::

            sage: # needs sage.symbolic
            sage: K = CyclotomicField(37)
            sage: K.minkowski_bound().n()
            7.50857335698544e14
            sage: K.bach_bound().n()
            191669.304126267

        The bound of course also works for the rational numbers::

            sage: QQ.bach_bound()                                                       # needs sage.symbolic
            1"""
    @overload
    def bach_bound(self) -> Any:
        """NumberField.bach_bound(self)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 325)

        Return the Bach bound associated to this number field.

        Assuming the General Riemann Hypothesis, this is a bound `B` so
        that every integral ideal is equivalent modulo principal
        fractional ideals to an integral ideal of norm at most `B`.

        .. SEEALSO::

            :meth:`~minkowski_bound`

        OUTPUT: symbolic expression or the Integer 1

        EXAMPLES:

        We compute both the Minkowski and Bach bounds for a quadratic
        field, where the Minkowski bound is much better::

            sage: # needs sage.symbolic
            sage: K = QQ[sqrt(5)]
            sage: K.minkowski_bound()
            1/2*sqrt(5)
            sage: K.minkowski_bound().n()
            1.11803398874989
            sage: K.bach_bound()
            12*log(5)^2
            sage: K.bach_bound().n()
            31.0834847277628

        We compute both the Minkowski and Bach bounds for a bigger
        degree field, where the Bach bound is much better::

            sage: # needs sage.symbolic
            sage: K = CyclotomicField(37)
            sage: K.minkowski_bound().n()
            7.50857335698544e14
            sage: K.bach_bound().n()
            191669.304126267

        The bound of course also works for the rational numbers::

            sage: QQ.bach_bound()                                                       # needs sage.symbolic
            1"""
    @overload
    def bach_bound(self) -> Any:
        """NumberField.bach_bound(self)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 325)

        Return the Bach bound associated to this number field.

        Assuming the General Riemann Hypothesis, this is a bound `B` so
        that every integral ideal is equivalent modulo principal
        fractional ideals to an integral ideal of norm at most `B`.

        .. SEEALSO::

            :meth:`~minkowski_bound`

        OUTPUT: symbolic expression or the Integer 1

        EXAMPLES:

        We compute both the Minkowski and Bach bounds for a quadratic
        field, where the Minkowski bound is much better::

            sage: # needs sage.symbolic
            sage: K = QQ[sqrt(5)]
            sage: K.minkowski_bound()
            1/2*sqrt(5)
            sage: K.minkowski_bound().n()
            1.11803398874989
            sage: K.bach_bound()
            12*log(5)^2
            sage: K.bach_bound().n()
            31.0834847277628

        We compute both the Minkowski and Bach bounds for a bigger
        degree field, where the Bach bound is much better::

            sage: # needs sage.symbolic
            sage: K = CyclotomicField(37)
            sage: K.minkowski_bound().n()
            7.50857335698544e14
            sage: K.bach_bound().n()
            191669.304126267

        The bound of course also works for the rational numbers::

            sage: QQ.bach_bound()                                                       # needs sage.symbolic
            1"""
    @overload
    def bach_bound(self) -> Any:
        """NumberField.bach_bound(self)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 325)

        Return the Bach bound associated to this number field.

        Assuming the General Riemann Hypothesis, this is a bound `B` so
        that every integral ideal is equivalent modulo principal
        fractional ideals to an integral ideal of norm at most `B`.

        .. SEEALSO::

            :meth:`~minkowski_bound`

        OUTPUT: symbolic expression or the Integer 1

        EXAMPLES:

        We compute both the Minkowski and Bach bounds for a quadratic
        field, where the Minkowski bound is much better::

            sage: # needs sage.symbolic
            sage: K = QQ[sqrt(5)]
            sage: K.minkowski_bound()
            1/2*sqrt(5)
            sage: K.minkowski_bound().n()
            1.11803398874989
            sage: K.bach_bound()
            12*log(5)^2
            sage: K.bach_bound().n()
            31.0834847277628

        We compute both the Minkowski and Bach bounds for a bigger
        degree field, where the Bach bound is much better::

            sage: # needs sage.symbolic
            sage: K = CyclotomicField(37)
            sage: K.minkowski_bound().n()
            7.50857335698544e14
            sage: K.bach_bound().n()
            191669.304126267

        The bound of course also works for the rational numbers::

            sage: QQ.bach_bound()                                                       # needs sage.symbolic
            1"""
    @overload
    def bach_bound(self) -> Any:
        """NumberField.bach_bound(self)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 325)

        Return the Bach bound associated to this number field.

        Assuming the General Riemann Hypothesis, this is a bound `B` so
        that every integral ideal is equivalent modulo principal
        fractional ideals to an integral ideal of norm at most `B`.

        .. SEEALSO::

            :meth:`~minkowski_bound`

        OUTPUT: symbolic expression or the Integer 1

        EXAMPLES:

        We compute both the Minkowski and Bach bounds for a quadratic
        field, where the Minkowski bound is much better::

            sage: # needs sage.symbolic
            sage: K = QQ[sqrt(5)]
            sage: K.minkowski_bound()
            1/2*sqrt(5)
            sage: K.minkowski_bound().n()
            1.11803398874989
            sage: K.bach_bound()
            12*log(5)^2
            sage: K.bach_bound().n()
            31.0834847277628

        We compute both the Minkowski and Bach bounds for a bigger
        degree field, where the Bach bound is much better::

            sage: # needs sage.symbolic
            sage: K = CyclotomicField(37)
            sage: K.minkowski_bound().n()
            7.50857335698544e14
            sage: K.bach_bound().n()
            191669.304126267

        The bound of course also works for the rational numbers::

            sage: QQ.bach_bound()                                                       # needs sage.symbolic
            1"""
    @overload
    def degree(self) -> Any:
        """NumberField.degree(self)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 223)

        Return the degree of this number field.

        EXAMPLES::

            sage: x = polygen(ZZ)
            sage: NumberField(x^3 + 9, 'a').degree()
            3"""
    @overload
    def degree(self) -> Any:
        """NumberField.degree(self)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 223)

        Return the degree of this number field.

        EXAMPLES::

            sage: x = polygen(ZZ)
            sage: NumberField(x^3 + 9, 'a').degree()
            3"""
    @overload
    def discriminant(self) -> Any:
        """NumberField.discriminant(self)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 235)

        Return the discriminant of this number field.

        EXAMPLES::

            sage: x = polygen(ZZ)
            sage: NumberField(x^3 + 9, 'a').discriminant()
            -243"""
    @overload
    def discriminant(self) -> Any:
        """NumberField.discriminant(self)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 235)

        Return the discriminant of this number field.

        EXAMPLES::

            sage: x = polygen(ZZ)
            sage: NumberField(x^3 + 9, 'a').discriminant()
            -243"""
    def is_absolute(self) -> Any:
        """NumberField.is_absolute(self)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 191)

        Return ``True`` if ``self`` is viewed as a single extension over `\\QQ`.

        EXAMPLES::

            sage: x = polygen(ZZ)
            sage: K.<a> = NumberField(x^3 + 2)
            sage: K.is_absolute()
            True
            sage: y = polygen(K)
            sage: L.<b> = NumberField(y^2 + 1)
            sage: L.is_absolute()
            False
            sage: QQ.is_absolute()
            True"""
    @overload
    def maximal_order(self) -> Any:
        """NumberField.maximal_order(self)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 178)

        Return the maximal order, i.e., the ring of integers of this
        number field.

        EXAMPLES::

            sage: x = polygen(ZZ)
            sage: NumberField(x^3 - 2,'b').maximal_order()
            Maximal Order generated by b in Number Field in b with defining polynomial x^3 - 2"""
    @overload
    def maximal_order(self) -> Any:
        """NumberField.maximal_order(self)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 178)

        Return the maximal order, i.e., the ring of integers of this
        number field.

        EXAMPLES::

            sage: x = polygen(ZZ)
            sage: NumberField(x^3 - 2,'b').maximal_order()
            Maximal Order generated by b in Number Field in b with defining polynomial x^3 - 2"""
    def minkowski_bound(self) -> Any:
        """NumberField.minkowski_bound(self)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 247)

        Return the Minkowski bound associated to this number field.

        This is a bound `B` so that every integral ideal is equivalent
        modulo principal fractional ideals to an integral ideal of
        norm at most `B`.

        .. SEEALSO::

            :meth:`~bach_bound`

        OUTPUT: symbolic expression or Rational

        EXAMPLES:

        The Minkowski bound for `\\QQ[i]` tells us that the class
        number is 1::

            sage: # needs sage.symbolic
            sage: K = QQ[I]
            sage: B = K.minkowski_bound(); B
            4/pi
            sage: B.n()
            1.27323954473516

        We compute the Minkowski bound for `\\QQ[\\sqrt[3]{2}]`::

            sage: # needs sage.symbolic
            sage: K = QQ[2^(1/3)]
            sage: B = K.minkowski_bound(); B
            16/3*sqrt(3)/pi
            sage: B.n()
            2.94042077558289
            sage: int(B)
            2

        We compute the Minkowski bound for `\\QQ[\\sqrt{10}]`, which has class
        number 2::

            sage: # needs sage.symbolic
            sage: K = QQ[sqrt(10)]
            sage: B = K.minkowski_bound(); B
            sqrt(10)
            sage: int(B)
            3
            sage: K.class_number()
            2

        We compute the Minkowski bound for `\\QQ[\\sqrt{2}+\\sqrt{3}]`::

            sage: # needs sage.symbolic
            sage: x = polygen(ZZ)
            sage: K.<y,z> = NumberField([x^2 - 2, x^2 - 3])
            sage: L.<w> = QQ[sqrt(2) + sqrt(3)]
            sage: B = K.minkowski_bound(); B
            9/2
            sage: int(B)
            4
            sage: B == L.minkowski_bound()
            True
            sage: K.class_number()
            1

        The bound of course also works for the rational numbers::

            sage: QQ.minkowski_bound()
            1"""
    @overload
    def ring_of_integers(self, *args, **kwds) -> Any:
        """NumberField.ring_of_integers(self, *args, **kwds)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 153)

        Synonym for :meth:`maximal_order`.

        EXAMPLES::

            sage: x = polygen(ZZ)
            sage: K.<a> = NumberField(x^2 + 1)
            sage: K.ring_of_integers()
            Gaussian Integers generated by a in Number Field in a with defining polynomial x^2 + 1"""
    @overload
    def ring_of_integers(self) -> Any:
        """NumberField.ring_of_integers(self, *args, **kwds)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 153)

        Synonym for :meth:`maximal_order`.

        EXAMPLES::

            sage: x = polygen(ZZ)
            sage: K.<a> = NumberField(x^2 + 1)
            sage: K.ring_of_integers()
            Gaussian Integers generated by a in Number Field in a with defining polynomial x^2 + 1"""
    @overload
    def signature(self) -> Any:
        """NumberField.signature(self)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 210)

        Return `(r_1, r_2)`, where `r_1` and `r_2` are the number of real embeddings
        and pairs of complex embeddings of this field, respectively.

        EXAMPLES::

            sage: x = polygen(ZZ)
            sage: NumberField(x^3 - 2, 'a').signature()
            (1, 1)"""
    @overload
    def signature(self) -> Any:
        """NumberField.signature(self)

        File: /build/sagemath/src/sage/src/sage/rings/number_field/number_field_base.pyx (starting at line 210)

        Return `(r_1, r_2)`, where `r_1` and `r_2` are the number of real embeddings
        and pairs of complex embeddings of this field, respectively.

        EXAMPLES::

            sage: x = polygen(ZZ)
            sage: NumberField(x^3 - 2, 'a').signature()
            (1, 1)"""
